# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/igel/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/igel/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/igel/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/igel/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/compiler/CMakeFiles /d/compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named igel

# Build rule for target.
igel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 igel
.PHONY : igel

# fast build rule for target.
igel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/build
.PHONY : igel/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named libIg

# Build rule for target.
libIg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libIg
.PHONY : libIg

# fast build rule for target.
libIg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libIg.dir/build.make CMakeFiles/libIg.dir/build
.PHONY : libIg/fast

src/CompilerInfo/InfoParser.o: src/CompilerInfo/InfoParser.cpp.o
.PHONY : src/CompilerInfo/InfoParser.o

# target to build an object file
src/CompilerInfo/InfoParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/InfoParser.cpp.o
.PHONY : src/CompilerInfo/InfoParser.cpp.o

src/CompilerInfo/InfoParser.i: src/CompilerInfo/InfoParser.cpp.i
.PHONY : src/CompilerInfo/InfoParser.i

# target to preprocess a source file
src/CompilerInfo/InfoParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/InfoParser.cpp.i
.PHONY : src/CompilerInfo/InfoParser.cpp.i

src/CompilerInfo/InfoParser.s: src/CompilerInfo/InfoParser.cpp.s
.PHONY : src/CompilerInfo/InfoParser.s

# target to generate assembly for a file
src/CompilerInfo/InfoParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/InfoParser.cpp.s
.PHONY : src/CompilerInfo/InfoParser.cpp.s

src/CompilerInfo/OptionsParser.o: src/CompilerInfo/OptionsParser.cpp.o
.PHONY : src/CompilerInfo/OptionsParser.o

# target to build an object file
src/CompilerInfo/OptionsParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/OptionsParser.cpp.o
.PHONY : src/CompilerInfo/OptionsParser.cpp.o

src/CompilerInfo/OptionsParser.i: src/CompilerInfo/OptionsParser.cpp.i
.PHONY : src/CompilerInfo/OptionsParser.i

# target to preprocess a source file
src/CompilerInfo/OptionsParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/OptionsParser.cpp.i
.PHONY : src/CompilerInfo/OptionsParser.cpp.i

src/CompilerInfo/OptionsParser.s: src/CompilerInfo/OptionsParser.cpp.s
.PHONY : src/CompilerInfo/OptionsParser.s

# target to generate assembly for a file
src/CompilerInfo/OptionsParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/CompilerInfo/OptionsParser.cpp.s
.PHONY : src/CompilerInfo/OptionsParser.cpp.s

src/langMain/codeGen/Generator.o: src/langMain/codeGen/Generator.cpp.o
.PHONY : src/langMain/codeGen/Generator.o

# target to build an object file
src/langMain/codeGen/Generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/Generator.cpp.o
.PHONY : src/langMain/codeGen/Generator.cpp.o

src/langMain/codeGen/Generator.i: src/langMain/codeGen/Generator.cpp.i
.PHONY : src/langMain/codeGen/Generator.i

# target to preprocess a source file
src/langMain/codeGen/Generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/Generator.cpp.i
.PHONY : src/langMain/codeGen/Generator.cpp.i

src/langMain/codeGen/Generator.s: src/langMain/codeGen/Generator.cpp.s
.PHONY : src/langMain/codeGen/Generator.s

# target to generate assembly for a file
src/langMain/codeGen/Generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/Generator.cpp.s
.PHONY : src/langMain/codeGen/Generator.cpp.s

src/langMain/codeGen/types.o: src/langMain/codeGen/types.cpp.o
.PHONY : src/langMain/codeGen/types.o

# target to build an object file
src/langMain/codeGen/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/types.cpp.o
.PHONY : src/langMain/codeGen/types.cpp.o

src/langMain/codeGen/types.i: src/langMain/codeGen/types.cpp.i
.PHONY : src/langMain/codeGen/types.i

# target to preprocess a source file
src/langMain/codeGen/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/types.cpp.i
.PHONY : src/langMain/codeGen/types.cpp.i

src/langMain/codeGen/types.s: src/langMain/codeGen/types.cpp.s
.PHONY : src/langMain/codeGen/types.s

# target to generate assembly for a file
src/langMain/codeGen/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/codeGen/types.cpp.s
.PHONY : src/langMain/codeGen/types.cpp.s

src/langMain/parsing/Indexer.o: src/langMain/parsing/Indexer.cpp.o
.PHONY : src/langMain/parsing/Indexer.o

# target to build an object file
src/langMain/parsing/Indexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Indexer.cpp.o
.PHONY : src/langMain/parsing/Indexer.cpp.o

src/langMain/parsing/Indexer.i: src/langMain/parsing/Indexer.cpp.i
.PHONY : src/langMain/parsing/Indexer.i

# target to preprocess a source file
src/langMain/parsing/Indexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Indexer.cpp.i
.PHONY : src/langMain/parsing/Indexer.cpp.i

src/langMain/parsing/Indexer.s: src/langMain/parsing/Indexer.cpp.s
.PHONY : src/langMain/parsing/Indexer.s

# target to generate assembly for a file
src/langMain/parsing/Indexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Indexer.cpp.s
.PHONY : src/langMain/parsing/Indexer.cpp.s

src/langMain/parsing/Parser.o: src/langMain/parsing/Parser.cpp.o
.PHONY : src/langMain/parsing/Parser.o

# target to build an object file
src/langMain/parsing/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Parser.cpp.o
.PHONY : src/langMain/parsing/Parser.cpp.o

src/langMain/parsing/Parser.i: src/langMain/parsing/Parser.cpp.i
.PHONY : src/langMain/parsing/Parser.i

# target to preprocess a source file
src/langMain/parsing/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Parser.cpp.i
.PHONY : src/langMain/parsing/Parser.cpp.i

src/langMain/parsing/Parser.s: src/langMain/parsing/Parser.cpp.s
.PHONY : src/langMain/parsing/Parser.s

# target to generate assembly for a file
src/langMain/parsing/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/Parser.cpp.s
.PHONY : src/langMain/parsing/Parser.cpp.s

src/langMain/parsing/PreParser.o: src/langMain/parsing/PreParser.cpp.o
.PHONY : src/langMain/parsing/PreParser.o

# target to build an object file
src/langMain/parsing/PreParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/PreParser.cpp.o
.PHONY : src/langMain/parsing/PreParser.cpp.o

src/langMain/parsing/PreParser.i: src/langMain/parsing/PreParser.cpp.i
.PHONY : src/langMain/parsing/PreParser.i

# target to preprocess a source file
src/langMain/parsing/PreParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/PreParser.cpp.i
.PHONY : src/langMain/parsing/PreParser.cpp.i

src/langMain/parsing/PreParser.s: src/langMain/parsing/PreParser.cpp.s
.PHONY : src/langMain/parsing/PreParser.s

# target to generate assembly for a file
src/langMain/parsing/PreParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/langMain/parsing/PreParser.cpp.s
.PHONY : src/langMain/parsing/PreParser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tokenizer.o: src/tokenizer.cpp.o
.PHONY : src/tokenizer.o

# target to build an object file
src/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/tokenizer.cpp.o
.PHONY : src/tokenizer.cpp.o

src/tokenizer.i: src/tokenizer.cpp.i
.PHONY : src/tokenizer.i

# target to preprocess a source file
src/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/tokenizer.cpp.i
.PHONY : src/tokenizer.cpp.i

src/tokenizer.s: src/tokenizer.cpp.s
.PHONY : src/tokenizer.s

# target to generate assembly for a file
src/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/tokenizer.cpp.s
.PHONY : src/tokenizer.cpp.s

src/util/Mangler.o: src/util/Mangler.cpp.o
.PHONY : src/util/Mangler.o

# target to build an object file
src/util/Mangler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/util/Mangler.cpp.o
.PHONY : src/util/Mangler.cpp.o

src/util/Mangler.i: src/util/Mangler.cpp.i
.PHONY : src/util/Mangler.i

# target to preprocess a source file
src/util/Mangler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/util/Mangler.cpp.i
.PHONY : src/util/Mangler.cpp.i

src/util/Mangler.s: src/util/Mangler.cpp.s
.PHONY : src/util/Mangler.s

# target to generate assembly for a file
src/util/Mangler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/igel.dir/build.make CMakeFiles/igel.dir/src/util/Mangler.cpp.s
.PHONY : src/util/Mangler.cpp.s

srcLib/Array.o: srcLib/Array.cpp.o
.PHONY : srcLib/Array.o

# target to build an object file
srcLib/Array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libIg.dir/build.make CMakeFiles/libIg.dir/srcLib/Array.cpp.o
.PHONY : srcLib/Array.cpp.o

srcLib/Array.i: srcLib/Array.cpp.i
.PHONY : srcLib/Array.i

# target to preprocess a source file
srcLib/Array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libIg.dir/build.make CMakeFiles/libIg.dir/srcLib/Array.cpp.i
.PHONY : srcLib/Array.cpp.i

srcLib/Array.s: srcLib/Array.cpp.s
.PHONY : srcLib/Array.s

# target to generate assembly for a file
srcLib/Array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libIg.dir/build.make CMakeFiles/libIg.dir/srcLib/Array.cpp.s
.PHONY : srcLib/Array.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... igel"
	@echo "... libIg"
	@echo "... src/CompilerInfo/InfoParser.o"
	@echo "... src/CompilerInfo/InfoParser.i"
	@echo "... src/CompilerInfo/InfoParser.s"
	@echo "... src/CompilerInfo/OptionsParser.o"
	@echo "... src/CompilerInfo/OptionsParser.i"
	@echo "... src/CompilerInfo/OptionsParser.s"
	@echo "... src/langMain/codeGen/Generator.o"
	@echo "... src/langMain/codeGen/Generator.i"
	@echo "... src/langMain/codeGen/Generator.s"
	@echo "... src/langMain/codeGen/types.o"
	@echo "... src/langMain/codeGen/types.i"
	@echo "... src/langMain/codeGen/types.s"
	@echo "... src/langMain/parsing/Indexer.o"
	@echo "... src/langMain/parsing/Indexer.i"
	@echo "... src/langMain/parsing/Indexer.s"
	@echo "... src/langMain/parsing/Parser.o"
	@echo "... src/langMain/parsing/Parser.i"
	@echo "... src/langMain/parsing/Parser.s"
	@echo "... src/langMain/parsing/PreParser.o"
	@echo "... src/langMain/parsing/PreParser.i"
	@echo "... src/langMain/parsing/PreParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tokenizer.o"
	@echo "... src/tokenizer.i"
	@echo "... src/tokenizer.s"
	@echo "... src/util/Mangler.o"
	@echo "... src/util/Mangler.i"
	@echo "... src/util/Mangler.s"
	@echo "... srcLib/Array.o"
	@echo "... srcLib/Array.i"
	@echo "... srcLib/Array.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

